version: "4"
name: fullstack
services:
  mysql:
    container_name: demo-project
    image: mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=fullstack

  phpmyadmin:
    container_name: admin_poc
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456789
    depends_on:
      - mysql

volumes:
  mysql_data: